/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "Platform_Types.h"

//RCC define
#define RCC_BASE	0x40021000
#define RCC_APB2ENR	*(volatile uint32_t *)(RCC_BASE + 0x18)

//GPIO Port A define
#define GPIOA_BASE	0x40010800
#define GPIOA_CRL  	*(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH  	*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR  	*(volatile uint32_t *)(GPIOA_BASE + 0x0C)

//EXTI define
#define EXTI_BASE	0x40010400
#define EXTI_IMR	*(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR	*(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR		*(volatile uint32_t *)(EXTI_BASE + 0x14)

//AFIO define
#define AFIO_BASE		0x40010000
#define AFIO_EXTICR1	*(volatile uint32_t *)(AFIO_BASE + 0x08)

#define NVIC_ISER0	*(volatile uint32_t *)(0xE000E100)

void Clock_Init(void){
	RCC_APB2ENR |= 0b101;
}

void GPIOA_Init(void){
	//Port A pin 13 output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	//Port A pin 0 Floating input
	GPIOA_CRL |= 1<<2;
}

int main(void)
{
	Clock_Init();
	GPIOA_Init();
	AFIO_EXTICR1 = 0;
	EXTI_RTSR |= 1<<0;
	EXTI_IMR  |= 1<<0;
	NVIC_ISER0 |= 1<<6;

    while(1){

    }
}
void EXTI0_IRQHandler(void){
	GPIOA_ODR ^= 1<<13;
	EXTI_PR |= 1<<0;
}
