/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"
#include "LCD.h"
#include "Keypad.h"
#include "Stm32_F103C6_USART_Driver.h"

void Clock_Init(void){
	//Enable clock for port A and port B
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

uint16_t ch;

void interrupt_callback()
{
	MCAL_UART_ReceiveData_8B_NO_Parity(USART1, &ch, disable);
	MCAL_UART_SendData_8B(USART1, &ch, enable);
}
int main(void)
{
	USART_conf Usart_config;
	Clock_Init();
	Usart_config.BaudRate = USART_BaudRate_115200;
	Usart_config.HwFlowCtrl = USART_HwFlowCtrl_NONE;
	Usart_config.IRQ_EN = USART_IRQ_EN_RXNE;
	Usart_config.P_IRQ_CallBack = interrupt_callback;
	Usart_config.Parity = USART_Parity_Disable;
	Usart_config.PayLoad = USART_PayLoad_8B;
	Usart_config.StopBits = USART_StopBits_1B;
	Usart_config.USART_MODE = USART_MODE_TX_RX;

	MCAL_UART_Init(USART1, &Usart_config);
	MCAL_UART_GPIO_Set_Pins_NO_CTS_RTS(USART1);
	/* Loop forever */
	while(1)
	{

	}
}

