/*
 * LCD.c
 *
 *  Created on: 21 Sept 2024
 *      Author: minak
 */

#include "LCD.h"

void _delay_ms(uint32_t time){
	uint32_t i,j;
	for(i=0;i<time;i++){
		for(j=0;j<255;j++);
	}
}

void Check_LCD_is_busy(void){
	GPIO_PINConfig_t LCD_PIN;
	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_0;
	LCD_PIN.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_1;
	LCD_PIN.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_2;
	LCD_PIN.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_3;
	LCD_PIN.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_4;
	LCD_PIN.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_5;
	LCD_PIN.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_6;
	LCD_PIN.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_7;
	LCD_PIN.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	MCAL_GPIO_WritePin(LCD_Control, ReadWrite, GPIO_PIN_SET);
	MCAL_GPIO_WritePin(LCD_Control, RS_switch, GPIO_PIN_RESET);

	LCD_kick();

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_0;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_1;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_2;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_3;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_4;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_5;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_6;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_7;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	MCAL_GPIO_WritePin(LCD_Control, ReadWrite, GPIO_PIN_RESET);
}
void LCD_kick(void){
	MCAL_GPIO_WritePin(LCD_Control, EN_switch, GPIO_PIN_SET);
	_delay_ms(50);
	MCAL_GPIO_WritePin(LCD_Control, EN_switch, GPIO_PIN_RESET);
}
void LCD_send_a_command(unsigned char command){

	Check_LCD_is_busy();
//	LCD_PORT = command;
	MCAL_GPIO_WritePort(LCD_PORT, command);

	MCAL_GPIO_WritePin(LCD_Control, ReadWrite, GPIO_PIN_RESET);
	MCAL_GPIO_WritePin(LCD_Control, RS_switch, GPIO_PIN_RESET);

	LCD_kick();


}
void LCD_send_a_char(unsigned char character){

	Check_LCD_is_busy();

	MCAL_GPIO_WritePort(LCD_PORT, character);

	MCAL_GPIO_WritePin(LCD_Control, ReadWrite, GPIO_PIN_RESET);
	MCAL_GPIO_WritePin(LCD_Control, RS_switch, GPIO_PIN_SET);

	LCD_kick();


}
void LCD_send_a_string(char * string){
	Check_LCD_is_busy();
	int count = 0;
	while(*string > 0){
		count++;
		LCD_send_a_char(*string++);
		if(count==16){
			LCD_GOTO_XY(LCD_SECOND_LINE,0);
		}
		else if(count>=32){
			LCD_clear_screen();
			LCD_GOTO_XY(LCD_FIRST_LINE,0);
			count = 0;
		}
	}
}
void LCD_init(void){
	GPIO_PINConfig_t LCD_PIN;

	_delay_ms(20);

	LCD_PIN.GPIO_PIN_Number = EN_switch;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_Control, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = ReadWrite;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_Control, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = RS_switch;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_Control, &LCD_PIN);

	MCAL_GPIO_WritePin(LCD_Control, ReadWrite, GPIO_PIN_RESET);
	MCAL_GPIO_WritePin(LCD_Control, RS_switch, GPIO_PIN_RESET);
	MCAL_GPIO_WritePin(LCD_Control, EN_switch, GPIO_PIN_RESET);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_0;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_1;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_2;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_3;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_4;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_5;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_6;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);

	LCD_PIN.GPIO_PIN_Number = GPIO_PIN_7;
	LCD_PIN.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	LCD_PIN.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(LCD_PORT, &LCD_PIN);
	_delay_ms(15);

	LCD_clear_screen();


	LCD_send_a_command(LCD_FUNCTION_8BIT_2LINES);


	LCD_send_a_command(LCD_ENTRY_MODE);
	LCD_send_a_command(LCD_BEGIN_AT_FIRST_RAW);
	LCD_send_a_command(LCD_DISP_ON_CURSOR_BLINK);

}
void LCD_clear_screen(void){
	LCD_send_a_command(LCD_CLEAR_SCREEN);
}
void LCD_GOTO_XY(unsigned char line,unsigned char position){
	if(line == 0){
		if(position < 16 && position >= 0){
			LCD_send_a_command(0x80 + position);
		}
	}
	else if(line == 1){
		if(position < 16 && position >= 0){
			LCD_send_a_command(0xC0 + position);
		}
	}
}

